export const LOGIN_USER = "LOGIN_USER";
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const CREATE_DRAFT = "CREATE_DRAFT";
export const UPDATE_DRAFT_LOCATION = "UPDATE_DRAFT_LOCATION";
